/*
 * This file is part of AstroJournal.
 *
 * AstroJournal is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * AstroJournal is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with AstroJournal.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.astrojournal.gui;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.WindowConstants;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;


import org.astrojournal.generator.AJGenerator;


/**
 * A very minimal graphical user interface for running astrojournal without scripts.
 * 
 * @author Piero Dalle Pezze
 * @version 0.1
 * @since 10/09/2015
 */
public class AJMiniGUI extends javax.swing.JFrame {

  private static final long serialVersionUID = -7217707367091677434L;
    /**
     * Creates new form NewJFrame
     */
    public AJMiniGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        status = new JLabel();
        //status.setVisible(false);
        btnCreateJournal = new JButton();
        
        btnCreateJournal.addActionListener(new ActionListener() {
	  @Override
    public void actionPerformed(ActionEvent e) {
	    if(!isCreated) {
	    AJGenerator ajLatexGenerator = new AJGenerator();
	    String rawReportsFolder = "raw_reports/";
	    String latexReportsFolderByDate = "latex_reports_by_date/";
	    String latexReportsFolderByTarget = "latex_reports_by_target/";
      String sglReportsFolderByDate = "sgl_reports_by_date/";	    
	    new File(latexReportsFolderByDate).mkdir();
	    new File(latexReportsFolderByTarget).mkdir();    
      new File(sglReportsFolderByDate).mkdir();	    
	    // generate Latex code for the observation records
            ajLatexGenerator.generateJournals(rawReportsFolder, latexReportsFolderByDate, latexReportsFolderByTarget, sglReportsFolderByDate);
            // run pdflatex
	    try {
	        // The pdflatex command must be called two times in order to generate the list of contents correctly.
	      
	        // NOTE: for some reason Runtime.getRuntime().exec() works only if the command output is captured on Windows.
	        // On Linux, this does not matter, but on Windows this does not work.. So leave it.
        Process p = Runtime.getRuntime().exec("pdflatex astrojournal_by_date.tex");
          
           // read the output messages from the command
           BufferedReader stdInput = new BufferedReader(new
           InputStreamReader(p.getInputStream()));
           System.out.println("Command output:\n");
           String temp;
           while ((temp = stdInput.readLine()) != null) {
           System.out.println(temp);
           }
          
           // read the error messages from the command
           BufferedReader stdError = new BufferedReader(new
           InputStreamReader(p.getErrorStream()));
           System.out.println("\nCommand output error:\n");
           while ((temp = stdError.readLine()) != null) {
           System.out.println(temp);
           }
          
          p = Runtime.getRuntime().exec("pdflatex astrojournal_by_date.tex");
          
          // read the output messages from the command
          stdInput = new BufferedReader(new
          InputStreamReader(p.getInputStream()));
          System.out.println("Command output:\n");
          while ((temp = stdInput.readLine()) != null) {
          System.out.println(temp);
          }
         
          // read the error messages from the command
          stdError = new BufferedReader(new
          InputStreamReader(p.getErrorStream()));
          System.out.println("\nCommand output error:\n");
          while ((temp = stdError.readLine()) != null) {
          System.out.println(temp);
          }

          p = Runtime.getRuntime().exec("pdflatex astrojournal_by_target.tex");
          
          // read the output messages from the command
          stdInput = new BufferedReader(new
          InputStreamReader(p.getInputStream()));
          System.out.println("Command output:\n");
          while ((temp = stdInput.readLine()) != null) {
          System.out.println(temp);
          }
         
          // read the error messages from the command
          stdError = new BufferedReader(new
          InputStreamReader(p.getErrorStream()));
          System.out.println("\nCommand output error:\n");
          while ((temp = stdError.readLine()) != null) {
          System.out.println(temp);
          }          
          
          p = Runtime.getRuntime().exec("pdflatex astrojournal_by_target.tex");

          
          // read the output messages from the command
          stdInput = new BufferedReader(new
          InputStreamReader(p.getInputStream()));
          System.out.println("Command output:\n");
          while ((temp = stdInput.readLine()) != null) {
          System.out.println(temp);
          }
         
          // read the error messages from the command
          stdError = new BufferedReader(new
          InputStreamReader(p.getErrorStream()));
          System.out.println("\nCommand output error:\n");
          while ((temp = stdError.readLine()) != null) {
          System.out.println(temp);
          }
          
          p = Runtime.getRuntime().exec("rm -rf *.aux *.toc *.log *.out");
          
          // read the output messages from the command
          stdInput = new BufferedReader(new
          InputStreamReader(p.getInputStream()));
          System.out.println("Command output:\n");
          while ((temp = stdInput.readLine()) != null) {
          System.out.println(temp);
          }
         
          // read the error messages from the command
          stdError = new BufferedReader(new
          InputStreamReader(p.getErrorStream()));
          System.out.println("\nCommand output error:\n");
          while ((temp = stdError.readLine()) != null) {
          System.out.println(temp);
          }
          
          status.setText("Journals should be created!");
          btnCreateJournal.setText("Close");
          isCreated = true;
        } catch (IOException ioe) { }

        } else {
          dispose();
        }
    }
  });
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnCreateJournal.setText("Create Journals");

        status.setText(" ");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(status)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateJournal)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateJournal)
                .addGap(27, 27, 27)
                .addComponent(status)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AJMiniGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AJMiniGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AJMiniGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AJMiniGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AJMiniGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCreateJournal;
    private JLabel status;
    private boolean isCreated = false;
    // End of variables declaration//GEN-END:variables
}
