/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.astrojournal.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JToolBar;
import javax.swing.SwingConstants;

/**
 *
 * @author npdp
 */
public class AJToolbar extends javax.swing.JPanel {

    /**
     * Creates new form AJMenubar
     */
    public AJToolbar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AJToolbar = new javax.swing.JToolBar();
        btnGenerateJournal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSearchTarget = new javax.swing.JButton();
        txtSearchTarget = new javax.swing.JTextField();

        AJToolbar.setFloatable(false);
        AJToolbar.setRollover(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/astrojournal/gui/Bundle"); // NOI18N
        btnGenerateJournal.setText(bundle.getString("AJToolbar.btnGenerateJournal.text")); // NOI18N
        btnGenerateJournal.setToolTipText(bundle.getString("AJToolbar.btnGenerateJournal.toolTipText")); // NOI18N
        btnGenerateJournal.setFocusable(false);
        btnGenerateJournal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerateJournal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AJToolbar.add(btnGenerateJournal);
        AJToolbar.add(jSeparator1);

        btnSearchTarget.setText(bundle.getString("AJToolbar.btnSearchTarget.text")); // NOI18N
        btnSearchTarget.setToolTipText(bundle.getString("AJToolbar.btnSearchTarget.toolTipText")); // NOI18N
        btnSearchTarget.setFocusable(false);
        btnSearchTarget.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchTarget.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AJToolbar.add(btnSearchTarget);

        txtSearchTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTargetActionPerformed(evt);
            }
        });
        AJToolbar.add(txtSearchTarget);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(AJToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AJToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchTargetActionPerformed(ActionEvent evt) {//GEN-FIRST:event_txtSearchTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTargetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar AJToolbar;
    private javax.swing.JButton btnGenerateJournal;
    private javax.swing.JButton btnSearchTarget;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JTextField txtSearchTarget;
    // End of variables declaration//GEN-END:variables
}
