/*
 * Author: Piero Dalle Pezze
 * Version: 0.1
 * Created on: 28/05/2015
 */
package org.astrojournal;


/**
 * The Header of the Latex main file.
 */
public class AJLatexHeaderFooter {
    
    /** The header of the Latex main file. */
    private static String header =
	"\\documentclass[10pt,twoside,a4paper]{article}\n" +
	"\\usepackage[a4paper,margin=1in,landscape]{geometry}\n" +
	"\\usepackage{color}\n" +
	"\\usepackage{graphicx}\n" +
	"\\usepackage{longtable}\n" +
	"\\usepackage{pdflscape}\n" +
	"% DO NOT EDIT THIS FILE AS IT IS AUTO-GENERATED by the program AstroJournal. \n" +
	"\\title{Astronomy Observation Journal}\n" +
	"\\author{Piero Dalle Pezze}\n" +
	"\\date{\\today}\n" +
	"\\begin{document}\n" +
	"\\maketitle\n" +
	"\\begin{abstract}\n" +
	"This document contains a collection of observation reports. It is auto-generated by running Java program " +
	"AstroJournal (https://pdp10@bitbucket.org/pdp10/astrojournal.git) and the utility pdflatex (or texi2pdf). AstroJournal generates Latex code from tab-separated value (tsv) files " +
	"exported using a SpreadSheet (e.g. Google Drive SpreadSheet). This allows users to: a) edit their observation reports using a spreadsheet easily, b) obtain a complete and formatted report in Latex, and c) benefit from versioning (if using a versioning system such as Git). \n" +
	"\\end{abstract}\n" +
	
	"\n\n% Preamble. \n" +
	"\\newpage\n" +
	
	"\\footnotesize\n\n" +
	
	"\\noindent \n" +
	
	"{\\bf Atlases:}\n" +
	"\\begin{enumerate}  \n" +
	"\\item Deep Sky Hunter Star Atlas v2 (by Michael Vlasov)\n" +
	"\\item Sky \\& Telescope's Pocket Sky Atlas (by Roger W. Sinnott)\n" +
	"\\item Carte du Ciel (software)\n" +
	"\\item Stellarium on tablet (software)\n" +
	"\\end{enumerate}\n" +
	
	"\\bigskip \n" +
	"{\\bf Observing techniques for DSO:}\n" +
	"\\begin{enumerate}\n" +
	"\\item Eye adaptation at the eyepiece for 10min at least \n" +
	"\\item Averted vision \n" +
	"\\item Cover the other eye to relax the observing eye nerve \n" +
	"\\item Know exact target position (precise star hopping) \n" +
	"\\end{enumerate} \n" +
	
	"\\bigskip \n" +
	"{\\bf Antoniadi Scale:}\n" +
	"\\begin{enumerate}\n" +
	"\\item Perfect seeing, without a quiver.\n" +
	"\\item Slight undulations, with moments of calm lasting several seconds.\n" +
	"\\item Moderate seeing, with larger air tremors.\n" +
	"\\item Poor seeing, with constant troublesome undulations.\n" +
	"\\item Very bad seeing, scarcely allowing the makings of a rough sketch.\n" +
	"\\end{enumerate}\n" +
	
	"\\bigskip \n" +    
	"{\\bf Transparency Scale (American Association of Amateur Astronomers):}\n" +
	"\\begin{enumerate}\n" +
	"\\item Do Not Observe - Completely cloudy or precipitating. (Why are you out?)\n" +
	"\\item Very Poor - Mostly Cloudy. \n" +
	"\\item Poor - Partly cloudy or heavy haze. 1 or 2 Little Dipper stars visible. \n" +
	"\\item Somewhat Clear - Cirrus or moderate haze. 3 or 4 Little Dipper stars visible. \n" +
	"\\item Partly Clear - Slight haze. 4 or 5 Little Dipper stars visible. \n" +
	"\\item Clear - No clouds. Milky Way visible with averted vision. 6 Little Dipper stars visible. \n" +
	"\\item Very Clear - Milky Way and M31 visible. Stars fainter than mag 6.0 are just seen and fainter parts of the Milky Way are more obvious \n" +
	"\\item Extremely Clear - overwhelming profusion of stars, Zodiacal light and the gegenschein form continuous band across the sky, the Milky Way is very wide and bright throughout\n" +
	"\\end{enumerate}\n" +
	"\\newpage\n\n";


    /** The footer of the Latex document. */
    private static String footer = "\\end{document}\n";
    
    /**
     * Returns the header of the document.
     * @return header;
     */
    public static String getHeader() { return header; }

    /**
     * Returns the footer of the document.
     * @return footer;
     */
    public static String getFooter() { return footer; }
   
}
