/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.astrojournal;

/**
 *
 * @author npdp
 */
public class AJMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AJMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AJToolbar = new javax.swing.JToolBar();
        btnGenerateJournal = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSearchTarget = new javax.swing.JButton();
        txtSearchTarget = new javax.swing.JTextField();
        AJTabPanel = new javax.swing.JTabbedPane();
        tabPaneNewReport = new javax.swing.JPanel();
        labDate = new javax.swing.JLabel();
        labTime = new javax.swing.JLabel();
        labLocation = new javax.swing.JLabel();
        labAltitude = new javax.swing.JLabel();
        labTemperature = new javax.swing.JLabel();
        labSeeing = new javax.swing.JLabel();
        labTransparency = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        txtaltitude = new javax.swing.JTextField();
        txttemperature = new javax.swing.JTextField();
        labTelescopes = new javax.swing.JLabel();
        labEyepieces = new javax.swing.JLabel();
        labFilters = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txttelescopes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txteyepieces = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtfilters = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblobservation = new javax.swing.JTable();
        btnAddTarget = new javax.swing.JButton();
        btnRemoveTarget = new javax.swing.JButton();
        btnSubmitReport = new javax.swing.JButton();
        cbxtransparency = new javax.swing.JComboBox();
        cbxseeing = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txttime1 = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblreports = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        AJMenubar = new javax.swing.JMenuBar();
        menuMain = new javax.swing.JMenu();
        menuItemGenerateJournal = new javax.swing.JMenuItem();
        menuItemClose = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AJToolbar.setRollover(true);

        btnGenerateJournal.setText("Generate Journal");
        btnGenerateJournal.setToolTipText("Generate the astronomy observation journal");
        btnGenerateJournal.setFocusable(false);
        btnGenerateJournal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerateJournal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AJToolbar.add(btnGenerateJournal);
        AJToolbar.add(jSeparator1);

        btnSearchTarget.setText("Search Target");
        btnSearchTarget.setToolTipText("Search for a target (e.g. M42, NGC1502)");
        btnSearchTarget.setFocusable(false);
        btnSearchTarget.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearchTarget.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AJToolbar.add(btnSearchTarget);

        txtSearchTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchTargetActionPerformed(evt);
            }
        });
        AJToolbar.add(txtSearchTarget);

        AJTabPanel.setToolTipText("");

        tabPaneNewReport.setToolTipText("");

        labDate.setText("Date:");

        labTime.setText("Time:");

        labLocation.setText("Location:");

        labAltitude.setText("Altitude:");

        labTemperature.setText("Temperature:");

        labSeeing.setText("Seeing:");

        labTransparency.setText("Transparency:");

        txtdate.setToolTipText("Insert the date (e.g. 15/03/2015)");

        txttime.setToolTipText("Insert the starting time (e.g. 21:00)");

        txtlocation.setToolTipText("Insert the location (e.g. Cambridge, UK)");
        txtlocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocationActionPerformed(evt);
            }
        });

        txtaltitude.setToolTipText("Insert the location altitude (e.g. 12m)");

        txttemperature.setToolTipText("Insert the temperature (e.g. 5C (7km/h SSW) )");

        labTelescopes.setText("Telescopes:");

        labEyepieces.setText("Eyepieces:");

        labFilters.setText("Filters:");

        txttelescopes.setColumns(20);
        txttelescopes.setLineWrap(true);
        txttelescopes.setRows(5);
        txttelescopes.setToolTipText("Insert the list of telescopes used for this session");
        txttelescopes.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txttelescopes);

        txteyepieces.setColumns(20);
        txteyepieces.setLineWrap(true);
        txteyepieces.setRows(5);
        txteyepieces.setToolTipText("Insert the list of eyepieces used for this session");
        txteyepieces.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txteyepieces);

        txtfilters.setColumns(20);
        txtfilters.setLineWrap(true);
        txtfilters.setRows(5);
        txtfilters.setToolTipText("Insert the list of filters used for this session");
        txtfilters.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtfilters);

        tblobservation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Target", "Constellation", "Type", "Power", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblobservation.setColumnSelectionAllowed(true);
        jScrollPane5.setViewportView(tblobservation);
        tblobservation.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnAddTarget.setText("Add Target");
        btnAddTarget.setToolTipText("Add a new observed target to this report");
        btnAddTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTargetActionPerformed(evt);
            }
        });

        btnRemoveTarget.setText("Remove Target");
        btnRemoveTarget.setToolTipText("Remove the selected target entry");
        btnRemoveTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTargetActionPerformed(evt);
            }
        });

        btnSubmitReport.setText("Submit Report");
        btnSubmitReport.setToolTipText("Submit the report when completed");
        btnSubmitReport.setEnabled(false);
        btnSubmitReport.setFocusable(false);
        btnSubmitReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmitReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        cbxtransparency.setEditable(true);
        cbxtransparency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 - Do not observe", "2 - Very poor", "3 - Poor", "4 - Somewhat clear", "5 - Partly clear", "6 - Clear", "7 - Very clear", "8 - Extremely clear" }));
        cbxtransparency.setSelectedIndex(5);
        cbxtransparency.setToolTipText("Select the transparency condition (AAAA Transparency scale by default, but you can insert other values)");
        cbxtransparency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtransparencyActionPerformed(evt);
            }
        });

        cbxseeing.setEditable(true);
        cbxseeing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 - Perfect seeing", "2 - Slightly undulations", "3 - Moderate seeing", "4 - Poor seeing", "5 - Very bad seeing" }));
        cbxseeing.setSelectedIndex(1);
        cbxseeing.setToolTipText("Select the seeing condition (Antoniadi scale by default, but you can insert other values)");
        cbxseeing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxseeingActionPerformed(evt);
            }
        });

        jLabel1.setText("-");

        txttime1.setToolTipText("Insert the ending time (e.g. 0:00)");

        javax.swing.GroupLayout tabPaneNewReportLayout = new javax.swing.GroupLayout(tabPaneNewReport);
        tabPaneNewReport.setLayout(tabPaneNewReportLayout);
        tabPaneNewReportLayout.setHorizontalGroup(
            tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaneNewReportLayout.createSequentialGroup()
                        .addComponent(btnAddTarget)
                        .addGap(9, 9, 9)
                        .addComponent(btnRemoveTarget)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmitReport))
                    .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                        .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabPaneNewReportLayout.createSequentialGroup()
                                    .addComponent(labTransparency)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxtransparency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabPaneNewReportLayout.createSequentialGroup()
                                    .addComponent(labSeeing)
                                    .addGap(67, 67, 67)
                                    .addComponent(cbxseeing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labDate)
                                    .addComponent(labTime)
                                    .addComponent(labLocation)
                                    .addComponent(labAltitude)
                                    .addComponent(labTemperature))
                                .addGap(24, 24, 24)
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                                        .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txttime1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtlocation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtaltitude, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttemperature, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdate))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTelescopes)
                            .addComponent(labEyepieces)
                            .addComponent(labFilters))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        tabPaneNewReportLayout.setVerticalGroup(
            tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                        .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                        .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labDate)
                                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labTime)
                                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(txttime1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labTelescopes)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labEyepieces)
                            .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labLocation)
                                    .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labAltitude)
                                    .addComponent(txtaltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labFilters)
                            .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labTransparency)
                                    .addComponent(cbxtransparency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tabPaneNewReportLayout.createSequentialGroup()
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labTemperature)
                                    .addComponent(txttemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxseeing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labSeeing))))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabPaneNewReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveTarget)
                    .addComponent(btnAddTarget)
                    .addComponent(btnSubmitReport, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        AJTabPanel.addTab("New Report", tabPaneNewReport);

        tblreports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Location", "Seeing", "Transparency", "Telescope", "Power", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblreports.setColumnSelectionAllowed(true);
        tblreports.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblreports);
        tblreports.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        AJTabPanel.addTab("Target", jPanel1);

        jSeparator2.setOrientation(javax.swing.SwingConstants.HORIZONTAL);

        menuMain.setText("Main");

        menuItemGenerateJournal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        menuItemGenerateJournal.setText("Generate Journal");
        menuItemGenerateJournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGenerateJournalActionPerformed(evt);
            }
        });
        menuMain.add(menuItemGenerateJournal);

        menuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuItemClose.setText("Close");
        menuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCloseActionPerformed(evt);
            }
        });
        menuMain.add(menuItemClose);

        AJMenubar.add(menuMain);

        menuAbout.setText("About");

        menuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        menuItemAbout.setText("About AstroJournal");
        menuAbout.add(menuItemAbout);

        AJMenubar.add(menuAbout);

        setJMenuBar(AJMenubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AJToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(AJTabPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AJToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(AJTabPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchTargetActionPerformed

    private void menuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCloseActionPerformed

    private void menuItemGenerateJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGenerateJournalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemGenerateJournalActionPerformed

    private void cbxseeingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxseeingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxseeingActionPerformed

    private void cbxtransparencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtransparencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtransparencyActionPerformed

    private void btnRemoveTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveTargetActionPerformed

    private void btnAddTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTargetActionPerformed

    private void txtlocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlocationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            // Don't use Nimbus because it does not work well..
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AJMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AJMenubar;
    private javax.swing.JTabbedPane AJTabPanel;
    private javax.swing.JToolBar AJToolbar;
    private javax.swing.JButton btnAddTarget;
    private javax.swing.JButton btnGenerateJournal;
    private javax.swing.JButton btnRemoveTarget;
    private javax.swing.JButton btnSearchTarget;
    private javax.swing.JButton btnSubmitReport;
    private javax.swing.JComboBox cbxseeing;
    private javax.swing.JComboBox cbxtransparency;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labAltitude;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labEyepieces;
    private javax.swing.JLabel labFilters;
    private javax.swing.JLabel labLocation;
    private javax.swing.JLabel labSeeing;
    private javax.swing.JLabel labTelescopes;
    private javax.swing.JLabel labTemperature;
    private javax.swing.JLabel labTime;
    private javax.swing.JLabel labTransparency;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemClose;
    private javax.swing.JMenuItem menuItemGenerateJournal;
    private javax.swing.JMenu menuMain;
    private javax.swing.JPanel tabPaneNewReport;
    private javax.swing.JTable tblobservation;
    private javax.swing.JTable tblreports;
    private javax.swing.JTextField txtSearchTarget;
    private javax.swing.JTextField txtaltitude;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextArea txteyepieces;
    private javax.swing.JTextArea txtfilters;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextArea txttelescopes;
    private javax.swing.JTextField txttemperature;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttime1;
    // End of variables declaration//GEN-END:variables
}
