/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.astrojournal.gui.advancedGUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author npdp
 */
public class AJMessageDialogue extends javax.swing.JDialog {

    /** Creates new form AJMessageDialogue */
    public AJMessageDialogue(java.awt.Frame parent, boolean modal) {
	super(parent, modal);
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jPanel1 = new JPanel();
	lblMessage = new JLabel();
	btnOK = new JButton();

	setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

	lblMessage.setHorizontalAlignment(SwingConstants.CENTER);
	ResourceBundle bundle = ResourceBundle.getBundle("locale/Bundle"); // NOI18N
	lblMessage.setText(bundle
		.getString("AJMessageDialogue.lblMessage.text")); // NOI18N
	lblMessage.setAutoscrolls(true);

	btnOK.setText(bundle.getString("AJMessageDialogue.btnOK.text")); // NOI18N
	btnOK.addActionListener(new ActionListener() {
	    @Override
	    public void actionPerformed(ActionEvent evt) {
		btnOKActionPerformed(evt);
	    }
	});

	GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
	jPanel1.setLayout(jPanel1Layout);
	jPanel1Layout.setHorizontalGroup(jPanel1Layout
		.createParallelGroup(GroupLayout.Alignment.LEADING)
		.addGroup(
			jPanel1Layout
				.createSequentialGroup()
				.addContainerGap()
				.addComponent(lblMessage,
					GroupLayout.DEFAULT_SIZE,
					GroupLayout.DEFAULT_SIZE,
					Short.MAX_VALUE).addContainerGap())
		.addGroup(
			GroupLayout.Alignment.TRAILING,
			jPanel1Layout.createSequentialGroup()
				.addContainerGap(113, Short.MAX_VALUE)
				.addComponent(btnOK).addGap(111, 111, 111)));
	jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
		GroupLayout.Alignment.LEADING).addGroup(
		jPanel1Layout
			.createSequentialGroup()
			.addComponent(lblMessage, GroupLayout.PREFERRED_SIZE,
				56, GroupLayout.PREFERRED_SIZE)
			.addPreferredGap(
				LayoutStyle.ComponentPlacement.RELATED,
				GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
			.addComponent(btnOK).addContainerGap()));

	GroupLayout layout = new GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout.createParallelGroup(
		GroupLayout.Alignment.LEADING).addComponent(jPanel1,
		GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
		Short.MAX_VALUE));
	layout.setVerticalGroup(layout.createParallelGroup(
		GroupLayout.Alignment.LEADING).addComponent(jPanel1,
		GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
		GroupLayout.PREFERRED_SIZE));

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(ActionEvent evt) {// GEN-FIRST:event_btnOKActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	// <editor-fold defaultstate="collapsed"
	// desc=" Look and feel setting code (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase
	 * /tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
		    .getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(
		    AJMessageDialogue.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(
		    AJMessageDialogue.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(
		    AJMessageDialogue.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(
		    AJMessageDialogue.class.getName()).log(
		    java.util.logging.Level.SEVERE, null, ex);
	}
	// </editor-fold>

	/* Create and display the dialog */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    @Override
	    public void run() {
		AJMessageDialogue dialog = new AJMessageDialogue(
			new javax.swing.JFrame(), true);
		dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		    @Override
		    public void windowClosing(java.awt.event.WindowEvent e) {
			System.exit(0);
		    }
		});
		dialog.setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnOK;
    private JPanel jPanel1;
    private JLabel lblMessage;
    // End of variables declaration//GEN-END:variables

}
