/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.astrojournal.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.ResourceBundle;
import javax.swing.GroupLayout;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JTabbedPane;
import javax.swing.KeyStroke;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author npdp
 */
public class AJMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public AJMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AJTabPanel = new JTabbedPane();
        ajNewTargetPanel = new AJNewTargetPanel();
        ajObservedTargetPanel = new AJObservedTargetPanel();
        ajToolbar = new AJToolbar();
        AJMenubar = new JMenuBar();
        menuMain = new JMenu();
        menuItemGenerateJournal = new JMenuItem();
        menuItemClose = new JMenuItem();
        menuAbout = new JMenu();
        menuItemAbout = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        ResourceBundle bundle = ResourceBundle.getBundle("resources/locale/Bundle"); // NOI18N
        AJTabPanel.setToolTipText(bundle.getString("AJMainGUI.AJTabPanel.toolTipText")); // NOI18N
        AJTabPanel.addTab(bundle.getString("AJMainGUI.ajNewTargetPanel.TabConstraints.tabTitle_1"), null, ajNewTargetPanel, bundle.getString("AJMainGUI.ajNewTargetPanel.TabConstraints.tabToolTip")); // NOI18N
        ajNewTargetPanel.getAccessibleContext().setAccessibleParent(AJTabPanel);

        AJTabPanel.addTab(bundle.getString("AJMainGUI.ajObservedTargetPanel.TabConstraints.tabTitle_1"), ajObservedTargetPanel); // NOI18N
        ajObservedTargetPanel.getAccessibleContext().setAccessibleParent(AJTabPanel);

        menuMain.setText(bundle.getString("AJMainGUI.menuMain.text_1")); // NOI18N

        menuItemGenerateJournal.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_G, InputEvent.CTRL_MASK));
        menuItemGenerateJournal.setText(bundle.getString("AJMainGUI.menuItemGenerateJournal.text_1")); // NOI18N
        menuItemGenerateJournal.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuItemGenerateJournalActionPerformed(evt);
            }
        });
        menuMain.add(menuItemGenerateJournal);

        menuItemClose.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_Q, InputEvent.CTRL_MASK));
        menuItemClose.setText(bundle.getString("AJMainGUI.menuItemClose.text_1")); // NOI18N
        menuItemClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                menuItemCloseActionPerformed(evt);
            }
        });
        menuMain.add(menuItemClose);

        AJMenubar.add(menuMain);

        menuAbout.setText(bundle.getString("AJMainGUI.menuAbout.text_1")); // NOI18N

        menuItemAbout.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, InputEvent.CTRL_MASK));
        menuItemAbout.setText(bundle.getString("AJMainGUI.menuItemAbout.text_1")); // NOI18N
        menuAbout.add(menuItemAbout);

        AJMenubar.add(menuAbout);

        setJMenuBar(AJMenubar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ajToolbar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(AJTabPanel)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ajToolbar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AJTabPanel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuItemCloseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCloseActionPerformed

    private void menuItemGenerateJournalActionPerformed(ActionEvent evt) {//GEN-FIRST:event_menuItemGenerateJournalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemGenerateJournalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            // Don't use Nimbus because it does not work well..
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AJMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AJMainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenuBar AJMenubar;
    private JTabbedPane AJTabPanel;
    private AJNewTargetPanel ajNewTargetPanel;
    private AJObservedTargetPanel ajObservedTargetPanel;
    private AJToolbar ajToolbar;
    private JMenu menuAbout;
    private JMenuItem menuItemAbout;
    private JMenuItem menuItemClose;
    private JMenuItem menuItemGenerateJournal;
    private JMenu menuMain;
    // End of variables declaration//GEN-END:variables
}
